---
title: "P8105_HW2_DI2251"
author: "di2251"
date: "2026-10-03"
output: github_document
---
```{r setup, echo=FALSE, message=FALSE}
library(haven)
library(tidyverse)
library(readxl)
library(ggridges)
```

### Problem 1

```{r data_import_q1}
NYC_subway = 
  read_csv(file = "data/NYC Transit Subway Data.csv", na = c("", "NA", ".")) |>
  janitor::clean_names()

NYC_subway
```

```{r select_q1}
NYC_subway = NYC_subway |>
  select(line, station_name, station_latitude, station_longitude, 
         starts_with("route"), entry, vending, entrance_type, ada) |>
  mutate(entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE))

NYC_subway
```


**Dataset description:**

**How many distinct stations are there?** *Note: stations are identified both by name and by line*

**How many stations are ADA compliant?**

**What proportion of station entrances/exits without vending allow entrance?**

### Problem 2

```{r data import_q2}
Trash_Wheel = read_excel(
  "data/Trash Wheel Collection Data 2025.xlsx",
  na = c("", "NA", ".")
)

Trash_Wheel = janitor::clean_names(Trash_Wheel)
```



### Problem 3

```{r data import_q3}
MCI_baseline = read_csv(
  file = "data/data_mci/MCI_baseline.csv",
  na = c("", "NA", ".")
)

MCI_baseline = janitor::clean_names(MCI_baseline)

MCI_amyloid = read_csv(
  file = "data/data_mci/mci_amyloid.csv",
  na = c("", "NA", ".")
)

MCI_amyloid = janitor::clean_names(MCI_amyloid)
```






